-- AlterTable
ALTER TABLE "stage2_pre_qualification" ADD COLUMN     "cash_out_amount" DECIMAL(12,2),
ADD COLUMN     "cash_out_amount_confirmed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "cash_out_use" TEXT,
ADD COLUMN     "closing_costs_preference" TEXT,
ADD COLUMN     "closing_costs_preference_confirmed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "current_mortgage_payment" DECIMAL(10,2),
ADD COLUMN     "current_mortgage_payment_confirmed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "current_mortgage_rate" DECIMAL(5,3),
ADD COLUMN     "current_mortgage_rate_confirmed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "current_mortgage_type" TEXT,
ADD COLUMN     "first_mortgage_balance" DECIMAL(12,2),
ADD COLUMN     "first_mortgage_balance_confirmed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "heloc_draw_period_understood" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "heloc_draw_use" TEXT,
ADD COLUMN     "heloc_line_amount" DECIMAL(12,2),
ADD COLUMN     "heloc_line_amount_confirmed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "heloc_prior" TEXT,
ADD COLUMN     "heloc_prior_confirmed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "heloc_rate_comfort" TEXT,
ADD COLUMN     "heloc_rate_comfort_confirmed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "heloc_repayment_period_understood" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "heloc_risk_acknowledged" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "heloc_timeline" TEXT,
ADD COLUMN     "heloc_timeline_confirmed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "prior_refinance" TEXT,
ADD COLUMN     "prior_refinance_confirmed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "property_value" DECIMAL(12,2),
ADD COLUMN     "property_value_confirmed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "refinance_subtrack" TEXT,
ADD COLUMN     "remaining_term_years" INTEGER,
ADD COLUMN     "remaining_term_years_confirmed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "stay_duration_years" TEXT,
ADD COLUMN     "stay_duration_years_confirmed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "va_subsequent_use" BOOLEAN;

-- AlterTable
ALTER TABLE "stage3_application" ADD COLUMN     "contact_name_confirmed" BOOLEAN NOT NULL DEFAULT false;
